### ISSUE TITLE
Ideia de logotipo para o projeto

### ISSUE THREAD

**Issue by kvnol** [DanielHe4rt/livecoding4noobs#2]
salve salve, @DanielHe4rt 

montei uma ideia de logo para o projeto, idealizei um conceito de livecoding para que o logo tivesse um real significado

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/3299130/184505662-40f3307f-59e1-4e5c-85d6-a0cf0e66b404.png">

**Comment by danielhe4rt** [comment]
por mim tá aprovado

**Comment by danielhe4rt** [comment]
LGTM

**Comment by danielhe4rt** [comment]
nice
